classDiagram

class AnimalBase
class PlantBase
class Pollinator
class Herbivore

AnimalBase <|-- Pollinator
AnimalBase <|-- Herbivore

Pollinator --> PlantBase : pollinates
Herbivore --> PlantBase : eats